# Generated by Django 5.1.2 on 2024-10-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Bookname',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Horror', 'Comedy'), ('Fiction', 'Non Fiction'), ('Science Fiction', 'Fantasy'), ('Mystery', 'Thriller'), ('Romance', 'Historical Fiction'), ('Biography', 'Autobiography'), ('Self-Help', 'Philosophy'), ('Poetry', 'Drama'), ('Adventure', 'Crime'), ('Young Adult', 'Children’s Literature'), ('Graphic Novel', 'Manga'), ('Dystopian', 'Memoir'), ('Spirituality', 'Health & Wellness'), ('Travel', 'Cookbook')], max_length=20, null=True),
        ),
    ]
